name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Render Deploy Action

        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
              # ID of the service to deploy
            service-id: ${{secrets.MY_RENDER_SERVICE_ID}}
              # A Render API key
            api-key: ${{secrets.MY_RENDER_API_KEY}}
